# Список серверов нашего приложения.
# 'app' - это имя сервиса из docker-compose.yml.
# Docker Compose автоматически разрешит это имя в IP-адрес контейнера.
upstream fastapi_app {
    server app:8000;
}

server {
    listen 80;
    server_name localhost;
    charset utf-8;

    # Если у вас есть домен, раскомментируйте и впишите его:
    # server_name your_domain.com;

    location / {
        # Перенаправляем все запросы на наше приложение
        proxy_pass http://fastapi_app;

        # Устанавливаем заголовки, чтобы приложение знало,
        # от кого на самом деле пришел запрос.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
